#!/usr/bin/python
import pronouncing
import subprocess
import sys
import json
import random
import re
import sys

def get_compiler():
	program_name = sys.argv[0]
	if "gado++" in program_name:
		compiler_name = "g++"
	elif "gado" in program_name:
		compiler_name = "gcc"
	else:
		# TODO: treat errors better
		print("error: program name not recognized")
		sys.exit(1)
	return compiler_name

# execute gcc with subprocess and get output
def get_gcc_output():
	json_format = "-fdiagnostics-format=json"
	compiler_name = get_compiler()
	
	# TODO: maybe use some parser instead of json, as it is only avaliable in newer versions of gcc.
	gcc_arglist = [compiler_name] + sys.argv[1:] + [json_format]

	gcc_output = subprocess.run(gcc_arglist, capture_output=True)
	error_log = gcc_output.stderr.decode().split('\n')[0]
	
	try:
		error_log_dict = json.loads(error_log)
	except:
		print("error: log is not in json format")
		sys.exit(1)
	
	error_messages = []
	for gcc_error in error_log_dict:
		formatted_error = gcc_error["message"]
		error_messages.append([formatted_error])
	return error_messages
	

# for each line of the output, get the last word
# (or a equivalent word, if there isn't rhymes avaliable)
def last_word(line):
	only_alphanum = re.sub("[^0-9a-zA-Z]+", " ", line)
	only_alphanum_lower = only_alphanum.lower()
	only_alphanum_list = only_alphanum_lower.split()
	return only_alphanum_list[-1]

# open the database and get the rhyme for each word
def get_poetry_db():
	with open('data/poetry.json') as poetry_db:
		return json.load(poetry_db)

# for each word, get a rhyme at random from the database
def get_rhyme(word, poetry_db):
	word_rhymes = pronouncing.rhymes(word)
	verse_rhymes = []
	for word_rhyme in word_rhymes:
		if word_rhyme in poetry_db:
			verse_rhymes.extend(poetry_db[word_rhyme])
	if len(verse_rhymes) != 0:
		return random.choice(verse_rhymes)
	else:
		return "rhyme not found :("

# print formatted rhymes
# something like
#
# Wishing me like to one more rich in hope,
# ‘number_of_args_mismatch’ was not declared in this scope
# (line 15, col 1)
#
# By unions married, do offend thine ear,
# ‘char many_chars’ previously declared here
# (line 32, col 23)
if __name__ == "__main__":
	gcc_output = get_gcc_output()
	poetry_db = get_poetry_db()
	for gcc_error in gcc_output:
		error_message = gcc_error[0]
		rhyming_with_error = get_rhyme(last_word(error_message), poetry_db)
		print(rhyming_with_error)
		print(error_message)
		print()
