#!/usr/bin/python
import pronouncing
import subprocess
import sys
import json

# execute gcc with subprocess
# TODO: maybe use some parser instead of json, as it is only avaliable in newer versions of gcc.

text_format = "-fdiagnostics-format=text"
json_format = "-fdiagnostics-format=json"

gcc_arglist_dirty = ["g++"] + sys.argv[1:]
gcc_arglist = [x for x in gcc_arglist_dirty if x != text_format and x != json_format]
gcc_arglist.append(json_format)

gcc_output = subprocess.run(gcc_arglist, capture_output=True)
error_log = gcc_output.stderr.decode().split('\n')[0]
print(error_log)
json.loads(error_log)

'''
try:
	json.loads(error_log)
except:
	print("json was not correctly loaded.")
	exit()
'''
# get output

# for each line of the output, get the last word
# (or a equivalent word, if there isn't rhymes avaliable)

# for each word, get a rhyme at random from the database

# print formatted rhymes
# something like
#
# Wishing me like to one more rich in hope,
# ‘number_of_args_mismatch’ was not declared in this scope
# (line 15, col 1)
#
# By unions married, do offend thine ear,
# ‘char many_chars’ previously declared here
# (line 32, col 23)

# profit